services:
  - type: web
    name: airbnb-scraper
    env: node
    buildCommand: |
      apt-get update &&
      apt-get install -y chromium-browser &&
      npm install
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
